stages:
  load_data:
    cmd: python src/data/make_dataset.py
    deps:
      - src/data/make_dataset.py
    outs:
      - data/raw/cifar-10-batches-py

  preprocess:
    cmd: python src/data/preprocess_data.py
    deps:
      - src/data/preprocess_data.py
      - data/raw/cifar-10-batches-py
    outs:
      - data/processed

  train:
    cmd: python src/models/train_model.py
    deps:
      - src/models/train_model.py
      - src/models/model.py
      - data/processed
    outs:
      - models
